from .compat import basestring as basestring, urlparse as urlparse
from .cookies import extract_cookies_to_jar as extract_cookies_to_jar
from .exceptions import ConnectTimeout as ConnectTimeout, ConnectionError as ConnectionError, InvalidHeader as InvalidHeader, InvalidProxyURL as InvalidProxyURL, InvalidSchema as InvalidSchema, InvalidURL as InvalidURL, ProxyError as ProxyError, ReadTimeout as ReadTimeout, RetryError as RetryError, SSLError as SSLError
from .models import Response as Response
from .structures import CaseInsensitiveDict as CaseInsensitiveDict
from .utils import DEFAULT_CA_BUNDLE_PATH as DEFAULT_CA_BUNDLE_PATH, extract_zipped_paths as extract_zipped_paths, get_auth_from_url as get_auth_from_url, get_encoding_from_headers as get_encoding_from_headers, prepend_scheme_if_needed as prepend_scheme_if_needed, select_proxy as select_proxy, urldefragauth as urldefragauth
from _typeshed import Incomplete

DEFAULT_POOLBLOCK: bool
DEFAULT_POOLSIZE: int
DEFAULT_RETRIES: int
DEFAULT_POOL_TIMEOUT: Incomplete

class BaseAdapter:
    def __init__(self) -> None: ...
    def send(self, request, stream: bool = ..., timeout: Incomplete | None = ..., verify: bool = ..., cert: Incomplete | None = ..., proxies: Incomplete | None = ...) -> None: ...
    def close(self) -> None: ...

class HTTPAdapter(BaseAdapter):
    __attrs__: Incomplete
    max_retries: Incomplete
    config: Incomplete
    proxy_manager: Incomplete
    def __init__(self, pool_connections=..., pool_maxsize=..., max_retries=..., pool_block=...) -> None: ...
    poolmanager: Incomplete
    def init_poolmanager(self, connections, maxsize, block=..., **pool_kwargs) -> None: ...
    def proxy_manager_for(self, proxy, **proxy_kwargs): ...
    def cert_verify(self, conn, url, verify, cert) -> None: ...
    def build_response(self, req, resp): ...
    def get_connection(self, url, proxies: Incomplete | None = ...): ...
    def close(self) -> None: ...
    def request_url(self, request, proxies): ...
    def add_headers(self, request, **kwargs) -> None: ...
    def proxy_headers(self, proxy): ...
    def send(self, request, stream: bool = ..., timeout: Incomplete | None = ..., verify: bool = ..., cert: Incomplete | None = ..., proxies: Incomplete | None = ...): ...
