import datetime
from .compat import Callable, List
from typing import Any, Optional, TypeVar, Union

T = TypeVar('T', bound=Callable)

def typed_list(datatype: T) -> Callable[[Optional[List]], List[T]]: ...
def int_or_error(x: Any) -> int: ...
def str_or_error(x: Any) -> str: ...
def bool_or_error(x: Any) -> bool: ...
def dict_or_error(x: Any) -> dict: ...
def str_or_dict_or_error(x: Any) -> Union[str, dict]: ...
def yandex_date(string: str) -> datetime.datetime: ...
def is_operation_link(link: str) -> bool: ...
def is_resource_link(url: str) -> bool: ...
def is_public_resource_link(url: str) -> bool: ...
def ensure_path_has_schema(path: str, default_schema: str = ...) -> str: ...
